[package]
name = "rust_light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.4.0"
itertools="0.10.5"
rayon = "1.7.0"


[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.0"
